- include_vars: vars.yml
- include: roles/kafka/templates/facts.yml
- name: Install required items
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk-headless
- name: Create ZK User
  user: name=zookeeper shell=/bin/bash
- name: Extract kafka
  unarchive:
    src: http://apache.claz.org/kafka/0.10.1.0/kafka_2.11-0.10.1.0.tgz
    remote_src: yes
    dest: /usr/local
    owner: kafka
    creates: /usr/local/kafka_2.11-0.10.1.0/
- name: Check if Kafka is running
  command: sh -c "ps aux|grep [S]CREEN"
  ignore_errors: yes
  changed_when: false
  register: service_kafka
- name: Copy kafka configs
  template: src=server.properties dest=/usr/local/kafka_2.11-0.10.1.0/config/server.properties
- name: Start Kafka
  command: screen -S kafka -d -m su - kafka /usr/local/kafka_2.11-0.10.1.0/bin/kafka-server-start.sh /usr/local/kafka_2.11-0.10.1.0/config/server.properties
  when: service_kafka | failed